spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${DB_PASSWORD}

server:
  servlet:
    session:
      cookie:
        secure: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

portfolio:
  file:
    storage-root: ${FILE_STORAGE_ROOT:/app/storage}
  swagger:
    enabled: true
    public-access: false
